### DISCUSSION TITLE
Airflow variables and connection management: review and moving forward

### DISCUSSION THREAD

**Discussion by sarayourfriend** [WordPress/openverse#4865] [Ideas]
At least twice the topic of how best to manage Airflow variables has come up in conversations between me, @stacimc, and @AetherUnbound. Most recently, [Staci brought it up in this comment thread on a PR introducing a new variable](https://github.com/WordPress/openverse/pull/4833#discussion_r1744264933):

> We could make an infrastructure change to set it as an environment variable though; actually, I'm not clear how we've drawn the line between which variables should be configured where 🤔 What do you think?
>
> ­­— @stacimc

To understand Staci's question, and the general question I'm wanting to resolve in this discussion, recall that [Airflow has three distinct methods for managing variables](https://airflow.apache.org/docs/apache-airflow/stable/howto/variable.html). In order of precedence, they are ([order retrieved from this Astronomer.io forum thread](https://forum.astronomer.io/t/what-precedence-does-airflow-determine-when-searching-for-a-single-connection/)):

- [Secrets Backend](https://airflow.apache.org/docs/apache-airflow-providers/core-extensions/secrets-backends.html)
- [Environment Variable](https://airflow.apache.org/docs/apache-airflow/stable/howto/variable.html#storing-variables-in-environment-variables)
- [Airflow UI/Metadata Database](https://airflow.apache.org/docs/apache-airflow/stable/howto/variable.html#)

We do not have a secrets backend defined, so the two options available to us are environment variables and the Airflow UI.

In previous discussions, we've [decided to use the metastore, configured through the UI (private infrastructure repository issue)](https://github.com/WordPress/openverse-infrastructure/issues/215). **That may well be the best path forward still**. However, I wanted to revisit this (the "through the UI" part of that) in light of Staci's question, and because the previous decision was made before we had set up Ansible as a way of interacting with the Airflow API.

---

A bit of background to set the stage... feel free to skip this if you understand why using a UI to manage application configuration is not always ideal.

Generally speaking, we prefer to configure the environment variables of our services in code. That is part of our Infrastructure as Code (IaC) practice. The primary motivators for IaC for environment variables are:

- to provide a history of changes to variables over time
- to ensure the motivation for changes are documented (e.g., through commit messages)
- to provide visibility of changes, including sometimes to provide opportunity for review of changes by at least one person before they are applied[^review]
- to provide a standard mechanism for auditable changes to variables, as sometimes required for complete rotation of secrets (in other words, it's harder to check whether something's been rotated in a UI compared to in code)

[^review]: Though, whether a change to the environment variables of a service requires review before applying them is up to the Opener making or proposing the change to decide. In some situations (i.e., after a discussion), we might apply changes before review. In others, there is an emergent situation requiring changes from an SRE perspective. Which is to say: _review_ is a notable feature of, but not always a necessary aspect of, environment variable management. Mostly the goal is visibility before or after the fact, irrespective of whether a critical review is required.

We use IaC to manage all environment variables/application (or runtime) configuration for the following services:

- Openverse frontend
- Openverse API
- Kibana
- Elasticsearch nodes
- Grafana PDC
- CI/CD environments (GitHub Variables/Secrets)

For Kibana and Elasticsearch, we manage a combination of environment variables and configuration files, so there is precedence and sometimes necessity of keeping a combination of both for various reasons.

We use IaC to manage _some_ variables for Airflow, but not all. Of the methods listed above available for Airflow variable management, we only use environment variables for our IaC managed variables. We manage the following as environment variables for Airflow in our Airflow Ansible role:

- Airflow settings that must be configured using environment variables or an Airflow configuration file
- Some but not all connection strings, including database connections, Slack endpoints, AWS connections
- Some things we've introduced as environment variables specifically, rather than Airflow variables (search for `getenv` in the catalogue code to find these). [I've open an issue to address these](https://github.com/WordPress/openverse/issues/4863).

Everything else, including API keys for providers we ingest from, and more recent additions of configuration settings that may have previous gone into environment-variable only things, are all managed through the Airflow UI. The rest of this discussion should assume we've written our code (or updated it in #4863) so that we can always and reliably retrieve variables from the metastore.

---

Given all three methods of variable configuration can be retrieved through the Metastore `Variable.get` and related APIs, we can still decide how best to manage variables.

As noted above [we have already decided to use the metastore to configure Airflow Variables](https://github.com/WordPress/openverse-infrastructure/issues/215), and I don't think we need to revisit that discussion. That is, we certainly do not need to move variables towards configuration only via the environment (the opposite of #4863). Additionally, we do not need to invest in the complexity of the remote Secrets Backends now (regardless of if ever).

**Instead, I propose we continue to use the Metastore (in line with previous decisions), but start managing them using the Airflow REST API, via our Ansible role for Airflow.**

The Airflow REST API exposes endpoints for managing variables and connections:

- Variables (GET, POST): https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#operation/get_variables
- Connections (GET, POST): https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#operation/get_connections

Using these endpoints, we can augment our existing Ansible role with the ability to sync variables and connections, even if no other changes exist, and bypass the Airflow restart step in these cases.

We would define connections and variables in the Airflow secrets `group_vars` as a YAML structure, mirroring the REST API's structure. For example, the `SILENCED_SLACK_NOTIFICATIONS` variable would be defined like so in `group_vars`.

```yaml
airflow_variables:
    - key: SILENCED_SLACK_NOTIFICATIONS
      value: |
        {}
      description: |
        DAG configuration overrides for the provider ingestion workflows. Currently only supports overriding the execution timeout for certain tasks, but allows dynamic overrides at DAG run time. Mapping of DAG ID to a list of dictionaries containing the following keys: "task_id" (a regex pattern that matches the task_id of the task to be modified), and "timeout" (str in "%d:%H:%M:%S" format giving the amount of time the task may take, example: 6d:10h:30m).
        
        Declaration: https://github.com/WordPress/openverse/blob/2cffcb9f8da6961e84a00854a3cd472fd0f9dad8/catalog/dags/providers/provider_workflows.py#L42-L58
        
        Example:
        
        {
            "brooklyn_museum_workflow": [
                {
                    "task_id_pattern": "pull_image_data",
                    "timeout": "10h"
                }
            ]
        }

    - key: ...
      value: ...
      description: ...
```

Connections would look like this:

```yaml
airflow_connections:
    - connection_id: ELASTICSEARCH_STAGING
      conn_type: Elasticsearch
      description: etc
      host: elasticsearch.internal
      port: 9200
    
    - connection_id: GITHUB_API
      conn_type: HTTP
      schema: https
      host: api.github.com
```

Because these YAML structures mirror the REST API's interfaces for variables/connections, it is trivial to export our current configuration to this format.

The role tasks would go something like this:

1. Read the variables and connections from the Ansible role variables, sort them by identifier, and replace sensitive values with sha256 hashes
1. Pull the variables and connections from the API, and repeat the same sorting and hashing process from the previous step, but make sure to save the clear-text versions as well, as we need them later when interacting with the API.
1. Generate a diff of the two and output it for confirmation.
1. If confirmed, split variables/connections into two groups for each type representing the upstream operations: one group for update/create and another for delete.
1. Iterate through the update/create variable group, and issue a POST request to `/api/v1/variables` with the variable. The POST request works both for updating an existing variable and to create a new one (provided you always supply the entire body of the POST request, which we will).
1. Iterate through the delete variable group, and issue a DELETE request to `/api/v1/variables/{{ variable.key }}` for each one.
1. Do the same iteration of update/create group and delete group for connections.

---

After this, the answer to Staci's original question will be: always manage variables using the Ansible definitions.

@WordPress/openverse-catalog what do y'all think of this? It's an attempt to bring the management of Airflow configuration/secrets, etc, closer in line with the rest of our applications.
