### ISSUE TITLE
Prevent concurrent action runs across all repositories

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#267]
## Problem

It is currently possible for someone to push a branch several times and trigger multiple concurrent runs of GitHub actions.

## Description

We can follow the example from the Gutenberg repository to prevent this:

```
# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name for pull requests
    # or the commit hash for any other events.
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true
```

https://github.com/WordPress/gutenberg/blob/trunk/.github/workflows/bundle-size.yml#L27-L32

This would need to be added to each action individually in each repository. There may be actions that should not have this but I'm not sure.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.
